# Generated by Django 5.1.7 on 2025-03-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_blogpost_review_like'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
